# Generated by Django 2.2 on 2019-12-03 11:33

from django.contrib.postgres.operations import CreateExtension
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),

        migrations.CreateModel(
            name='WasteDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Местоположение')),
                ('status', models.CharField(choices=[('new', '1')], default='1', max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Свалка',
                'verbose_name_plural': 'Свалки',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_received', models.DateTimeField(auto_now=True, verbose_name='Дата получения отчета')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Местоположение')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('feedback_info', models.TextField(blank=True, null=True, verbose_name='Обратная связь')),
                ('waste_deposit', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='reports',
                    to='reports.WasteDeposit', verbose_name='Свалка')
                 ),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ('pk',),
            },
        ),
    ]
