# Generated by Django 2.2.8 on 2020-01-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200103_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='verbose_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='report',
            name='was_sent',
            field=models.BooleanField(default=False, verbose_name='Включено в ежедневный отчет'),
        ),
    ]
