# Generated by Django 2.1.15 on 2020-01-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_contentcomplain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcomplain',
            options={'ordering': ('-datetime_received',), 'verbose_name': 'Жалоба на контент', 'verbose_name_plural': 'Жалобы на контент'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-pk',), 'verbose_name': 'Сообщение о свалке', 'verbose_name_plural': 'Сообщения о свалках'},
        ),
        migrations.AlterField(
            model_name='contentcomplain',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
