# Generated by Django 2.1.15 on 2020-02-17 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_add_default_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.State', verbose_name='Область'),
        ),
    ]
