# Generated by Django 2.1.15 on 2020-05-03 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastedeposit',
            options={'ordering': ('-pk',), 'verbose_name': 'Свалка', 'verbose_name_plural': 'Свалки'},
        ),
        migrations.AlterField(
            model_name='report',
            name='waste_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.WasteDeposit', verbose_name='Свалка'),
        ),
    ]
